version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=oj_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - oj-network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 300 config.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for judging
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_NAME=oj_system
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    privileged: true  # Required for Docker-in-Docker
    networks:
      - oj-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - oj-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  oj-network:
    driver: bridge

