# Generated by Django 4.2.7 on 2025-10-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=8080, verbose_name='端口')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU使用率')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='内存使用率')),
                ('task_count', models.IntegerField(default=0, verbose_name='当前任务数')),
                ('max_tasks', models.IntegerField(default=10, verbose_name='最大任务数')),
                ('total_judged', models.IntegerField(default=0, verbose_name='总判题数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='最后心跳')),
            ],
            options={
                'verbose_name': '判题服务器',
                'verbose_name_plural': '判题服务器',
                'db_table': 'judge_servers',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='语言名称')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('compile_command', models.TextField(blank=True, verbose_name='编译命令')),
                ('compile_timeout', models.IntegerField(default=30, verbose_name='编译超时(秒)')),
                ('run_command', models.TextField(verbose_name='运行命令')),
                ('template', models.TextField(blank=True, verbose_name='代码模板')),
                ('docker_image', models.CharField(max_length=200, verbose_name='Docker镜像')),
                ('file_extension', models.CharField(max_length=10, verbose_name='文件扩展名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
                'db_table': 'languages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(verbose_name='源代码')),
                ('code_length', models.IntegerField(verbose_name='代码长度')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('judging', '判题中'), ('finished', '已完成'), ('error', '系统错误')], db_index=True, default='pending', max_length=20, verbose_name='判题状态')),
                ('result', models.CharField(blank=True, choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compile Error'), ('SE', 'System Error'), ('PE', 'Presentation Error'), ('OLE', 'Output Limit Exceeded')], db_index=True, max_length=10, null=True, verbose_name='判题结果')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('pass_rate', models.FloatField(default=0.0, verbose_name='通过率')),
                ('time_used', models.IntegerField(blank=True, null=True, verbose_name='运行时间(ms)')),
                ('memory_used', models.IntegerField(blank=True, null=True, verbose_name='内存占用(KB)')),
                ('test_cases_passed', models.IntegerField(default=0, verbose_name='通过的测试用例数')),
                ('test_cases_total', models.IntegerField(verbose_name='总测试用例数')),
                ('compile_error', models.TextField(blank=True, verbose_name='编译错误信息')),
                ('runtime_error', models.TextField(blank=True, verbose_name='运行时错误信息')),
                ('error_testcase', models.IntegerField(blank=True, null=True, verbose_name='出错的测试用例编号')),
                ('judge_detail', models.JSONField(blank=True, default=dict, null=True, verbose_name='判题详情')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('judged_at', models.DateTimeField(blank=True, null=True, verbose_name='判题完成时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('shared', models.BooleanField(default=False, verbose_name='是否分享')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='judge.language', verbose_name='编程语言')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '代码提交',
                'verbose_name_plural': '代码提交',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='submissions_user_id_34eafe_idx'), models.Index(fields=['problem', 'result'], name='submissions_problem_cc94e0_idx'), models.Index(fields=['status', 'created_at'], name='submissions_status_3bfa4f_idx'), models.Index(fields=['user', 'result', 'created_at'], name='submissions_user_id_319fff_idx')],
            },
        ),
    ]
